### ISSUE TITLE
A "contextActivities" property contains one or more key/value pairs, why?

### ISSUE THREAD

**Issue by bscSCORM** [adlnet/lrs-conformance-test-suite#128]
The test which tests for 
> A "contextActivities" property contains one or more key/value pairs
lists the rationale of: `Data.md#2.4.6.2.s4.b2`

but that appears to be:

> Every value in the contextActivities Object MUST be either a single Activity Object or an array of Activity Objects.

Which is a requirement about the values that do exist, but does not appear to indicate that values in fact must exist.

At minimum it seems the rationale for the test needs to be updated.

**Comment by bscSCORM** [comment]
Note: I saw this issue as of 2efa2288ddaa4b7a0222b6b9392e8d249ce45daa (not suggesting it was caused by this commit, just noting the latest commit)

**Comment by ljwolford** [comment]
test and req should be removed (xapi-00095)
