### ISSUE TITLE
A Language Map is defined as an array of language tag/String pairs has at least 1 entry

### ISSUE THREAD

**Issue by bscSCORM** [adlnet/lrs-conformance-test-suite#129]
There is a section of tests based on:
> A Language Map is defined as an array of language tag/String pairs has at least 1 entry

However, there is no requirement listed with this assertion, nor could I find justification in the spec for the "at least 1 entry" assertion.

I think suggest we either drop these tests or provide a reference to why `{}` is not a valid language map.

**Comment by bscSCORM** [comment]
Note: I saw this issue as of 2efa2288ddaa4b7a0222b6b9392e8d249ce45daa (not suggesting it was caused by this commit, just noting the latest commit)

**Comment by ljwolford** [comment]
do not send empty language map. empty language maps should be ok for all instances for consistency. this should be fixed in the req doc. spec language around verb display should be edited and should be revisited in later revisions.
have a test send an empty language map and expect a 200
