### ISSUE TITLE
Wrong expected

### ISSUE THREAD

**Issue by castasamu** [adlnet/lrs-conformance-test-suite#132]
> "If the existing document does not have a Content-Type of application/json but the document being posted to the State Resource does the LRS MUST respond with HTTP status code 400 Bad Request, and MUST NOT update the target document as a result of the request."

> Error: Expected response status code to be 204 got 400

**Comment by cr8onski** [comment]
I think the error is coming in trying to PUT the "original" document which does expect a 204.  Once that document is established, the test tries to POST a document which does have Content-Type as application/json which is where the 400 is expected.  Let me know if that helps.

**Comment by castasamu** [comment]
ok, I'm sorry so mutch!! I was wrong!!!
