### ISSUE TITLE
Feature: run a single test

### ISSUE THREAD

**Issue by bscSCORM** [adlnet/lrs-conformance-test-suite#134]
It should be possible to specify a particular test to run. This makes it practical to attach a debugger to the LRS and watch how it handles a particular test, which is completely impractical for the entire suite or a directory.

**Comment by garemoko** [comment]
+1 to this feature request. 

Note though that you can re-run a collection of failed tests in the UI, a feature which I've found pretty much solves this use case for me. 

![image](https://cloud.githubusercontent.com/assets/1363163/22395564/2ad35590-e53a-11e6-8a01-fbebebb902e1.png)

**Comment by bscSCORM** [comment]
Oh, there is a `grep` option on the underlying tests, somehow I got hung up on `directory` and missed that. So, I'm going to close this, @garemoko if you really want this in the UI you could re-open it on the Grail issue tracker, but your workaround seems fine there. (and pointing it out made me realize there *must* already be a way to do what I want on the underlying tests, so I looked again and found `grep`).
