### ISSUE TITLE
Should reject DELETE with "activityId" with type... query parameters are strings

### ISSUE THREAD

**Issue by bscSCORM** [adlnet/lrs-conformance-test-suite#138]
It appears that the series of tests:

> Should reject DELETE with "activityId" with type ...

Expect the LRS to reject a `profileId` that could be parsed as something other than a string. Eg: `1`, or `true`.

That doesn't make sense because even though it's true we expect and require a string there, due to the nature of the query string it's not possible to pass something that's not a string. So even though `1` can be parsed as an integer, the LRS reasonably interprets it as the string `"1"`.

**Comment by TylerDixon** [comment]
This type of test appears to be duplicated across the non-statement resource APIs. Here's a few more instances:
* [Activities resource](https://github.com/adlnet/lrs-conformance-test-suite/blob/acaea76881215b683eb96fd5541cf572e8f876ae/test/v1_0_3/H.Communication2.5-ActivitiesResource.js#L94)
* [PUT agent profiles resource](https://github.com/adlnet/lrs-conformance-test-suite/blob/acaea76881215b683eb96fd5541cf572e8f876ae/test/v1_0_3/H.Communication2.6-AgentProfileResource.js#L139). 
* [PUT activity profiles resource](https://github.com/adlnet/lrs-conformance-test-suite/blob/acaea76881215b683eb96fd5541cf572e8f876ae/test/v1_0_3/H.Communication2.7-ActivityProfileResource.js#L139).

There's a few more cases in those files too (all dynamically generated with the `+ type`).

**Comment by bscSCORM** [comment]
Verified on 653096ad5fa064dab
