### ISSUE TITLE
Use agent instead profileId

### ISSUE THREAD

**Issue by castasamu** [adlnet/lrs-conformance-test-suite#140]
the test:
```javascript
 //Type "String" tests likely to be reworded or removed
    describe('An LRS\'s Activity Profile Resource rejects a GET request without "profileId" as a parameter if it is not type "String" with error code 400 Bad Request (format, Communication 2.7.s3.table1.row2)', function () {
      var document = helper.buildDocument(),
          invalidTypes = [1, true, { key: 'value'}];
      invalidTypes.forEach(function (type) {
          it('Should reject GET with "profileId" with type ' + type, function () {
              var parameters = helper.buildActivityProfile();
              parameters.agent = type;
              return helper.sendRequest('get', helper.getEndpointActivitiesProfile(), parameters, document, 400);
          });
      });
    });
```

set **agent** instead **profileId**.

Thanks!!!

**Comment by bscSCORM** [comment]
@castasamu , the Activities Profile resource doesn't take the `agent` parameter, but does take `profileId` see: https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#27-activity-profile-resource

I wonder if you're running into the issue I found here though: https://github.com/adlnet/lrs-conformance-test-suite/issues/138

**Comment by castasamu** [comment]
@bscSCORM infact si set the parameter *parameters.agent = type* but the description of test speaks of *profileId*...

Thanks a lot!
