### ISSUE TITLE
npm module `lrs-conformance-tests` should be maintained

### ISSUE THREAD

**Issue by bscSCORM** [adlnet/lrs-conformance-test-suite#141]
I see that there was an npm module registered for these tests, but it's out of date: https://www.npmjs.com/package/lrs-conformance-tests

I'd like to integrate the tests into our automated test process, and it would be preferable to just pull the module down from the npm repo (as we do with other tools for our tests) than to pull it down from github.

**Comment by FlorianTolk** [comment]
Hello! Unfortunately this user was not part of the adl team, and so we do not have access to his account. However, the newest version is now available as [https://www.npmjs.com/package/adl-lrs-conformance-tests](https://www.npmjs.com/package/adl-lrs-conformance-tests)

Thanks for pointing this out!
