### ISSUE TITLE
X-Experience-API-Consistent-Through not applied properly in "since" test

### ISSUE THREAD

**Issue by bscSCORM** [adlnet/lrs-conformance-test-suite#143]
The test:
> should only return statements stored after designated "since" timestamp when using "since" parameter

Appears to ignore the `X-Experience-API-Consistent-Through` header.

Note that both of the responses have a `X-Experience-API-Consistent-Through` earlier than specified since (`since=2017-01-31T22:13:06.508Z`), the later response has :  `x-experience-api-consistent-through: 2017-01-31T22:13:03.055Z`

That's over 3 seconds off, which makes me think that the "sync up the clocks" step is going wrong, rather than the LRS reporting a real 3+ second consistency delay. Regardless, the test shouldn't be able to say "success" or "fail" for this test, because the LRS hasn't caught up yet. It should fall back and wait longer.

Looking at this again, note:
> date: Tue, 31 Jan 2017 22:13:03 GMT

So as far as the LRS is concerned, the test wants statements from the future. So, there are probably two issues here -- the clock sync phase may not be reliable, and the test needs to back off more to handle `X-Experience-API-Consistent-Through`. Though what's really odd, is I'm running the tests on the same VM as the LRS being tested, so the clock shouldn't have any difference at all.

I'll leave that stream of consciousness up there in case someone else can make something of it, but the main point is: this test shouldn't have been marked a failure, it should have backed off about 3.5 seconds and retried.

```
FAILED: should only return statements stored after designated "since" timestamp when using "since" parameter

AssertionError: expected [] to include '0988a37a-c9b9-4da0-af64-d49d6d79629e'
REQUEST SUPERREQUEST
_______________________________________
GET /ScormEngineInterface/TCAPI/default/statements?verb=http://adlnet.gov/expapi/test/voided/target/26b64e5f-b4e5-4387-9cf8-5a960a86696e&since=2017-01-31T22:13:06.508Z HTTP/1.1
X-Experience-API-Version: 1.0.3
Authorization: Basic c2Nvcm06c2Nvcm0yMDA0
host: localhost:64619
Connection: close

RESPONSE SUPERREQUEST
_______________________________________
HTTP/1.1 200 OK
server: ASP.NET Development Server/11.0.0.0
date: Tue, 31 Jan 2017 22:13:03 GMT
x-aspnet-version: 4.0.30319
x-experience-api-version: 1.0.3
access-control-allow-origin: *
access-control-allow-methods: HEAD,GET,POST,PUT,DELETE
access-control-allow-headers: Content-Type,Content-Length,Authorization,If-Match,If-None-Match,X-Experience-API-Version,X-Experience-API-Consistent-Through
access-control-expose-headers: ETag,Last-Modified,Cache-Control,Content-Type,Content-Length,WWW-Authenticate,X-Experience-API-Version,X-Experience-API-Consistent-Through
x-experience-api-consistent-through: 2017-01-31T22:13:03.043Z
transfer-encoding: chunked
cache-control: private
content-type: application/json
connection: Close

{"statements":[],"more":""}
=======================================
REQUEST SUPERREQUEST
_______________________________________
GET /ScormEngineInterface/TCAPI/default/statements?verb=http://adlnet.gov/expapi/test/voided/target/26b64e5f-b4e5-4387-9cf8-5a960a86696e&since=2017-01-31T22:13:06.508Z HTTP/1.1
X-Experience-API-Version: 1.0.3
Authorization: Basic c2Nvcm06c2Nvcm0yMDA0
host: localhost:64619
Connection: close

RESPONSE SUPERREQUEST
_______________________________________
HTTP/1.1 200 OK
server: ASP.NET Development Server/11.0.0.0
date: Tue, 31 Jan 2017 22:13:03 GMT
x-aspnet-version: 4.0.30319
x-experience-api-version: 1.0.3
access-control-allow-origin: *
access-control-allow-methods: HEAD,GET,POST,PUT,DELETE
access-control-allow-headers: Content-Type,Content-Length,Authorization,If-Match,If-None-Match,X-Experience-API-Version,X-Experience-API-Consistent-Through
access-control-expose-headers: ETag,Last-Modified,Cache-Control,Content-Type,Content-Length,WWW-Authenticate,X-Experience-API-Version,X-Experience-API-Consistent-Through
x-experience-api-consistent-through: 2017-01-31T22:13:03.055Z
transfer-encoding: chunked
cache-control: private
content-type: application/json
connection: Close

{"statements":[],"more":""}
=======================================
```

**Comment by rchadwic** [comment]
I have a guess here, but I'll need you to test it for me, since I can't recreate this.

```
date: Tue, 31 Jan 2017 22:13:03 GMT
x-experience-api-consistent-through: 2017-01-31T22:13:03.055Z
```

You'll note that for encoding reasons, the consistent through time is a few MS in the future from res.headers.date. 

We have these lines of code, which attempt to guess how far behind real-time the consistent through is...  so if the server is consistent through 5 seconds before the current time, then we can guess that in 5 seconds it will be ready with our statement.

```
delta = new Date(res.headers.date).valueOf() - new Date(res.headers['x-experience-api-consistent-through']).valueOf();
finish = Date.now() + 10 * delta;
```

This does not appear to handle the case of the consistent through value being in the future of the headers.date. While not logically possible, it truncation of some milliseconds seems to make it possible to get a negative number. Then, when we should be waiting, we think we've waited long enough and stop waiting, failing the test. 

Let's try a Math.abs on this value. #76e4593.

Try that for me?

**Comment by bscSCORM** [comment]
@rchadwic , was this supposed to be a link? #76e4593

It sounds fairly likely this is what I ran into, but I won't really be able to verify it conclusively as I was running these tests repeatedly for a week before I hit this. I think there is another side of the bug, which is that you're trying to guess when the LRS will be consistent, but you should still verify on the request coming in before doing any other validation on that. If it's too complicated to wait longer and do another retry at that point, I suggest still having that check to say: "does the consistent through header make sense for what we're validating", and if not set the test status to "inconclusive" at least, so it's clear it just needs to be re-run.

Also note, although I'm not aware of any LRS that reports a variable amount of time to reach consistency, it's certainly valid to do so. So you could do your calculation and see that the LRS is 1 second behind, wait a second, and have the LRS come back and say it hadn't made any progress, it's now 2 seconds behind. So the tests should really account for that as well.

Sorry I can't conclusively verify the fix.

**Comment by rchadwic** [comment]
That's the commit number. I swear once upon a time they got autolinked. 

Yeah, we kicked around a lot of heuristics for guessing when we've waited long enough. We thought about tracking the delta - as in "is the LRS getting closer to real time, or farther? Can we fit a curve to some samples to get a good guess about when this statement might be available? " This led us to "is it valid for an LRS to never become consistent and every request state that it will be available around y3k?" Then we figured enough was enough and got a beer. 

You can see the algorithm in genDelay in helper.js. It seems to be.... 

1. If statement found - goto PASS
2. Else is LRS consistent past when we posted (plus time delta) - goto FAIL
3. Else do we have a predictions? If not - generate a prediction as described previously
4. Try once a second until past the prediction time.

I think that this would have worked for you, if the time delta was signed right - we would have tried again at absolute minimum 1 once more in 1 second. The margins here are pretty thin, so our 10 times the predicted delay still might not be good enough. We might take the min of the predicted delay and some guard value like 5s

**Comment by bscSCORM** [comment]
@rchadwic sounds like the `abs()` you put in should fix this, and I can't really say for sure if it does or not due to the very intermittent nature of this issue. I see 76e4593 is in `master`, so I'm going to close this and we can re-open if it comes up again.

Also note, it looks like you just need to leave the `#` off your commit numbers.
