### ISSUE TITLE
Statement Retrieval with Query Parameters Not Checking for Filtered Results

### ISSUE THREAD

**Issue by ahoran3** [adlnet/lrs-conformance-test-suite#144]
There are several instances where the tests are performing a `GET /statements` with query parameters but the only check run is that the response is a `200 OK` and  that the results have the structure: `{statements: [...]}` . 

This type of check is not validating that the LRS is actually returning what the request is expecting to receive. The same response could be sent back for each of these queries and these tests would not catch the flaw in the LRS.

Here are the tests:

[Query for Agent](https://github.com/adlnet/lrs-conformance-test-suite/blob/master/test/v1_0_3/E.Data2.5-RetrievalofStatements.js#L189) -- should check that the agent requested appears in each of the statements in the response

[Query for Verb](https://github.com/adlnet/lrs-conformance-test-suite/blob/master/test/v1_0_3/E.Data2.5-RetrievalofStatements.js#L212) -- should check that no statements in the response contain a verb other than the requested verb

[Query for Activity](https://github.com/adlnet/lrs-conformance-test-suite/blob/master/test/v1_0_3/E.Data2.5-RetrievalofStatements.js#L230)  -- should check that all statements in the response contain an object.id which matches the requested activityId

[Query for Registration](https://github.com/adlnet/lrs-conformance-test-suite/blob/master/test/v1_0_3/E.Data2.5-RetrievalofStatements.js#L248)  -- should check that all statements in the response contain object.id to the requested activityId

[Query for Related Activities](https://github.com/adlnet/lrs-conformance-test-suite/blob/master/test/v1_0_3/E.Data2.5-RetrievalofStatements.js#L266) -- should check that all statements in the response contain the the requested activityId in at least one of the: "object, any of the context Activities, or any of those properties in a contained SubStatement" (from [here](https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI-Communication.md#details-2))

[Query for Related Agents](https://github.com/adlnet/lrs-conformance-test-suite/blob/master/test/v1_0_3/E.Data2.5-RetrievalofStatements.js#L287) -- should check that all statements in the response contain the the requested agent in at least one of the: "Actor, Object, Authority, Instructor, Team, or any of these properties in a contained SubStatement" (from [here](https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI-Communication.md#details-2))

[Query for Since](https://github.com/adlnet/lrs-conformance-test-suite/blob/master/test/v1_0_3/E.Data2.5-RetrievalofStatements.js#L308) -- should check that all statements in the response contain timestamps more recent than the requested time

[Query for Until](https://github.com/adlnet/lrs-conformance-test-suite/blob/master/test/v1_0_3/E.Data2.5-RetrievalofStatements.js#L326) -- should check that all statements in the response contain timestamps prior to the requested time

[Query for Limit](https://github.com/adlnet/lrs-conformance-test-suite/blob/master/test/v1_0_3/E.Data2.5-RetrievalofStatements.js#L344) -- should check the appropriate number of statements were sent in the response

[Query for Ascending](https://github.com/adlnet/lrs-conformance-test-suite/blob/master/test/v1_0_3/E.Data2.5-RetrievalofStatements.js#L362) -- should check that all statements in the response are ordered according to their stored times

[Query for Format](https://github.com/adlnet/lrs-conformance-test-suite/blob/master/test/v1_0_3/E.Data2.5-RetrievalofStatements.js#L380) -- should check that all statements in the response are formatted according to the spec's formatting rules. Could also check that a single statement's structure is different when requested using format `ids` vs `canonical` vs `exact`.

**Comment by rchadwic** [comment]
I'm looking at "should return StatementResult with statements as array using GET with "agent"", and yeah, it looks like the test is not verifying that the results contain only statements with the agent. 

To be a bit pedantic about it, the requirement only mentions that the result be an array. There are a whole set of checks where the requirement just says "should be an array". Are these the ones? Also, anyone else on the team know if these implied requirements are hit elsewhere?

**Comment by cr8onski** [comment]
I though we did but I'm not finding them right now.  It looks like maybe we
don't.  Data 2.5 and Comm 2.1 are where I've been looking.

**Comment by rchadwic** [comment]
Ok, I've added a bunch of validation logic in ea4d863 . Note that the test cases don't explicitly test this behavior - like with the "until" - it's not as if we explicitly store statements, some of which are before and some of which are after the test date. Never the less, if we did, I think this logic would verify the results.
