### ISSUE TITLE
PUT request with If-None-Match header with ETag being tested when not in spec.

### ISSUE THREAD

**Issue by samcayford** [adlnet/lrs-conformance-test-suite#145]
The test here:
https://github.com/adlnet/lrs-conformance-test-suite/blob/master/test/v1_0_3/H.Communication3.1-Concurrency.js#L154
(`When responding to a PUT request, handle the If-None-Match header as described in RFC 2616, HTTP/1.1 if it contains an tag`)
is not testing anything in the spec, as far as i can tell.

The relevant part of the spec (https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#31-concurrency) only claims `An LRS responding to a PUT request MUST handle the "If-None-Match" header as described in RFC2616, HTTP 1.1 if it contains "*", in order to to detect when there is a resource present that the Client is not aware of.`.
This scenario is tested by the test directly below the one linked.

Maybe there was confusion with the requirement for `If-Match` which states `An LRS responding to a PUT request MUST handle the "If-Match" header as described in RFC2616, HTTP 1.1 if it contains an ETag, in order to detect modifications made after the Client last fetched the document.`.
This scenario is tested by the test directly above the one linked.

**Comment by rchadwic** [comment]
Hummmm. While I agree that I don't see this explicit requirement mentioned, does it not fall under the list of requirements, is it not implied by

>xAPI will use HTTP 1.1 entity tags (ETags) to implement optimistic concurrency

and 

>A Client making a PUT request to either the Agent Profile Resource or Activity Profile Resource MUST include the "If-Match" header or the If-None-Match header.

and 

>A Client making a POST request to either the Agent Profile Resource or Activity Profile Resource SHOULD* include the "If-Match" header or the If-None-Match header.

? This seems to be part of RCF2616 that is not explicitly listed.  Yeah reading over the spec, I can see an interpretation that this behavior is at best optional.

**Comment by ljwolford** [comment]
not a requirement, can be removed.
