### ISSUE TITLE
PUT with content body which is not url encoded -- no auth header

### ISSUE THREAD

**Issue by bscSCORM** [adlnet/lrs-conformance-test-suite#148]
> Expected response status code to be 400 got 401

Since there is no valid authentication header in this test, it seems like it should be OK to respond with either `401` or `400` -- it's a question of which requirements the LRS applies first, and I don't think we have anything which specifies that order.

Alternatively, you could just include the authentication header as a header, in which case it's fine to require the `400` response.

```
FAILED: will fail PUT with content body which is not url encoded

Error: Expected response status code to be 400 got 401
at (/Users/benclark/Projects/ripformance/test/v1_0_3/H.Communication1.3-AlternateRequestSyntax.js:137:14)
REQUEST SUPERREQUEST
_______________________________________
POST /ScormEngineInterface/TCAPI/default/statements?method=PUT HTTP/1.1
content-type: application/x-www-form-urlencoded
host: localhost
content-length: 467
Connection: close

{"statementId":"b0b99357-c906-40a2-8fcd-aabdf070b390","content":"{\"actor\":{\"objectType\":\"Agent\",\"name\":\"xAPI mbox\",\"mbox\":\"mailto:xapi@adlnet.gov\"},\"verb\":{\"id\":\"http://adlnet.gov/expapi/verbs/attended\",\"display\":{\"en-GB\":\"attended\",\"en-US\":\"attended\"}},\"object\":{\"objectType\":\"Activity\",\"id\":\"http://www.example.com/meetings/occurances/34534\"}}","X-Experience-API-Version":"1.0.3","Authorization":"Basic cm9vdDpzY29ybTIwMDQ="}

RESPONSE SUPERREQUEST
_______________________________________
HTTP/1.1 401 Unauthorized
date: Thu, 02 Feb 2017 21:05:20 GMT
server: Apache/2.4.18 (Unix)
x-experience-api-version: 0.9
access-control-allow-origin: *
access-control-allow-methods: HEAD,GET,POST,PUT,DELETE
access-control-allow-headers: Content-Type,Content-Length,Authorization,If-Match,If-None-Match,X-Experience-API-Version
access-control-expose-headers: ETag,Last-Modified,Cache-Control,Content-Type,Content-Length,WWW-Authenticate,X-Experience-API-Version
www-authenticate: Basic realm="SCORM Engine TCAPI"
content-length: 30
connection: close

Missing authentication header.
=======================================
```

**Comment by bscSCORM** [comment]
Cute. I just noticed we're responding via `0.9` there as well, which makes sense since there is no valid version header either.

**Comment by cr8onski** [comment]
As I understand it, the valid authorization and version headers are included as form parameters with the same names which should work since this is an alternate request syntax (?method=PUT).

**Comment by garemoko** [comment]
I guess what's happening then is that because the content body is not urlencoded, those parameters can't be read and therefore it's as though they are not there, i.e. they aren't there in a valid format.

**Comment by cr8onski** [comment]
Oh, you're right.  Didn't think of that part, that they aren't encoded so not really there nor valid.  I believe the best thing to do at this point is to make sure those headers are there for this test.
