### ISSUE TITLE
About check expects `1.0.0`

### ISSUE THREAD

**Issue by bscSCORM** [adlnet/lrs-conformance-test-suite#153]
The test:
> An LRS's About Resource's version property contains at least one string of "1.0.0" (Communication 2.8.s5.b1.b1, XAPI-00317)

Expects the `about` resource to include `1.0.0`, but it should expect `1.0.3`

This is based on the requirements:

An LRS MUST return the JSON document described above, with a "version" property that includes the latest minor and patch version the LRS conforms to, for each major version.
* For version 1.0.0 of this specification, this means that 1.0.0 MUST be included; 0.9 and 0.95 MAY be included. (For the purposes of this requirement, 0.9 and 0.95 are considered major versions.)

This is a bit of a confusing requirement, but note that it says: "For version 1.0.0 of this specification, this means that 1.0.0 MUST be included". Some important things to consider about this statement:
* "this means that" -- this requirement is subordinate to the requirement above, and clearly an example of that requirement. Where there is ambiguity, we should look back to that requirement (which would give us 1.0.3, not 1.0.0)
* "For version 1.0.0" -- this is not version 1.0.0 of the specification, it's version 1.0.3, so this requirement doesn't apply

found on: 653096ad5f

**Comment by garemoko** [comment]
Yeah, the wording there was deliberately to avoid having to update that line every patch version and inevitably forgetting.
