### ISSUE TITLE
Alternate Request Syntax attachment test not sending any attachments

### ISSUE THREAD

**Issue by TylerDixon** [adlnet/lrs-conformance-test-suite#159]
[The test in question](https://github.com/adlnet/lrs-conformance-test-suite/blob/acaea76881215b683eb96fd5541cf572e8f876ae/test/v1_0_3/H.Communication1.3-AlternateRequestSyntax.js#L127-L141). This test seems sketchy on 2 accounts:

1. From looking at the statement being sent to the endpoint, it sends a statement with an `attachments` property that is only an empty array.
2. The closest requirement to spec that I can find for this test is around [here](https://github.com/adlnet/xAPI-Spec/blob/5ef45de33cf7cb189d0e455e7829794a20418a42/xAPI-Communication.md#requirements):
  > Attachments: Note that due to issues relating to encoding, it is not possible to send binary data attachments using this syntax.

The test in this case isn't sending any attachments, and if it were, it would have to specify in some way (as I assume attachments with `fileUrl` sent as `application/json` would still be valid).

**Comment by bscSCORM** [comment]
see also: https://github.com/adlnet/grail-issue-tracker/issues/15

**Comment by cr8onski** [comment]
fixed in pr #126
