### ISSUE TITLE
Test making assumption on stored verb display properties

### ISSUE THREAD

**Issue by TylerDixon** [adlnet/lrs-conformance-test-suite#160]
[Test in question](https://github.com/adlnet/lrs-conformance-test-suite/blob/6229c42fe587418f93875bf8ed0daee4eb68a2fe/test/v1_0_3/H.Communication2.1-StatementResource.js#L1159-L1184). Most particularly [this line](https://github.com/adlnet/lrs-conformance-test-suite/blob/6229c42fe587418f93875bf8ed0daee4eb68a2fe/test/v1_0_3/H.Communication2.1-StatementResource.js#L1175) and [this line](https://github.com/adlnet/lrs-conformance-test-suite/blob/6229c42fe587418f93875bf8ed0daee4eb68a2fe/test/v1_0_3/H.Communication2.1-StatementResource.js#L1178).

Here, the test sends a statement and a substatement, both with a verb with an identical `id`, but the 2 verbs differ in their `display` property. Checking the returned statement in this test (and a few of the tests following this) expect both verbs to deep equal what was sent. With reference to statement immutability [here](https://github.com/adlnet/xAPI-Spec/blob/5ef45de33cf7cb189d0e455e7829794a20418a42/xAPI-Data.md#231-statement-immutability) in the spec:
> Verbs referenced by a Statement. The "display" property of the Verb is not considered part of the Statement itself (see the Statement Resource's "format" parameter for details).

It seems more correct that the tests (save `format: exact`) should only be testing a comparison of the verb IDs as opposed to a deep equal comparison of the verb objects.

**Comment by bscSCORM** [comment]
@TylerDixon the `format` parameter has a default of `exact` defined in the table below https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#213-get-statements
