### ISSUE TITLE
Agents Verify Templates: agents.default conflicts with statements.authority

### ISSUE THREAD

**Issue by milt** [adlnet/lrs-conformance-test-suite#175]
In the template verify test here: https://github.com/adlnet/lrs-conformance-test-suite/blob/master/test/v1_0_3/configs/verify.js#L83

Two templates are used which contain a conflicting name attribute for the same agent (identified by mbox):

[agents.default](https://github.com/adlnet/lrs-conformance-test-suite/blob/master/test/v1_0_3/templates/agents/default.json):

```json
{
  "objectType": "Agent",
  "name": "xAPI mbox",
  "mbox": "mailto:xapi@adlnet.gov"
}
```

[statements.authority](https://github.com/adlnet/lrs-conformance-test-suite/blob/master/test/v1_0_3/templates/statements/authority.json) (actor):

```json
...
"actor": {
    "objectType": "Agent",
    "name": "xAPI account",
    "mbox": "mailto:xapi@adlnet.gov"
  },
...
```

Note that here, `"name": "xAPI account"` rather than "xAPI mbox"

When combined [here](https://github.com/adlnet/lrs-conformance-test-suite/blob/master/test/v1_0_3/configs/verify.js#L83):

```javascript
                    {
                        name: 'should pass statement authority template',
                        templates: [
                            {statement: '{{statements.authority}}'},
                            {authority: '{{agents.default}}'}
                        ],
                        expect: [200]
                    },
```

Will yield a statement with conflicting name information for the agent. I realize the name is just a display property, but it doesn't seem correct for a single statement to assert that a given agent has two different names.

**Comment by milt** [comment]
Looks like a bunch of the statement templates have the same anomaly, in both the 1_0_2 and 1_0_3 dirs.

**Comment by garemoko** [comment]
The lrs is expected to return agents exactly as stored even when responding in canonical format. Since the lrs shouldn't behave any differently because of this weird inconsistency, it might be best to leave it in the tests.

**Comment by milt** [comment]
I don't know, that seems like a specific concern for tests about statement immutability and the GET resource, relying on hiding that intention in inconsistent templates files feels like a smell.
Moreover it *seems* like the pairing of agent ifi type and name in these template files was (at least originally) intentional (maybe someone can confirm that).

Personally I'd want the templates to be as minimal as possible (and therefore omit the name entirely), but I'd settle for consistency and specificity.
