### ISSUE TITLE
The test add statementId param in the request

### ISSUE THREAD

**Issue by castasamu** [adlnet/lrs-conformance-test-suite#177]
The [test](https://github.com/adlnet/lrs-conformance-test-suite/blob/master/test/v1_0_3/H.Communication2.1-StatementResource.js#L1347-L1373) add statementId in the request then the response has got one statement and **statements** property is not required.

```javascript
{
      // NOT REQUIRED BECOUSE THE RESPONSE HAS GOT 1 ITEM
      "statements": [
      ....
       ]
}
```

**Comment by cr8onski** [comment]
see https://github.com/adlnet/lrs-conformance-test-suite/issues/154

**Comment by castasamu** [comment]
Thanks @cr8onski and sorry!!
