### ISSUE TITLE
Two tests reporting wrong content-length header during multipart/mixed post in live test suite

### ISSUE THREAD

**Issue by tkelly42** [adlnet/lrs-conformance-test-suite#189]
The tests listed below incorrectly set the content-length to 1072 rather than the correct value of 1084.

The content-length is reported incorrected when testing via the live LRS Test Suite.  The issue doesn't present itself when testing locally on a windows based machine.

Affected Tests:

1.  An LRSs Statement Resource not return attachment data and only return application/json if the "attachment" parameter set to "false" (Communication 2.1.3.s1.b1)" 
2. The Statements within the "statements" property will correspond to the filtering criterion sent in with the GET request (Communication 2.1.3.s1) 

This causes an issue whereby the last few characters of the multi-part boundary is missed resulting in a malformed request.
 
A copy of the post data is below.  The body includin <CRLF> characters comes to 1084. This was verified manually and with Fiddler.

REQUEST SUPERREQUEST
_______________________________________
POST /xapi/statements HTTP/1.1
Content-Type: multipart/mixed; boundary=-------314159265358979323846
X-Experience-API-Version: 1.0.3
Authorization: Basic eGFwaXRlc3RhY2NvdW50Oi5ULXY0MiNlNDh2QmM=
host: lrsj18cloudapiapp.azurewebsites.net
content-length: 1072
Connection: close

---------314159265358979323846
Content-Type: application/json

{"actor":{"objectType":"Agent","mbox":"mailto:sample.agent@example.com","name":"Sample Agent"},"verb":{"id":"http://adlnet.gov/expapi/verbs/answered","display":{"en-US":"answered"}},"object":{"id":"http://www.example.com/tincan/activities/multipart","objectType":"Activity","definition":{"name":{"en-US":"Multi Part Activity"},"description":{"en-US":"Multi Part Activity Description"}}},"timestamp":"2014-07-11T13:51:03.971Z","attachments":[{"usageType":"http://example.com/attachment-usage/test","display":{"en-US":"A test attachment"},"contentType":"text/plain","length":27,"sha2":"495395e777cd98da653df9615d09c0fd6bb2f8d4788394cd53c56a3bfdcd848a","description":{"en-US":"A test attachment (description)"}}]}
---------314159265358979323846
Content-Disposition: attachment; filename="text_data.txt"
Content-Type: text/plain
Content-Transfer-Encoding: binary
X-Experience-API-Hash: 495395e777cd98da653df9615d09c0fd6bb2f8d4788394cd53c56a3bfdcd848a

here is a simple attachment
---------314159265358979323846--

RESPONSE SUPERREQUEST

**Comment by rchadwic** [comment]
How are you coming up with 1084? If you check out the actual binary payload that is loaded, you should get 1071 bytes. There is an additional newline added, so 1072 is the correct number. We load the attachment data in raw binary mode, so there should be no character encoding voodoo messing with the computed sizes.

Is it possible that the tool you're using to count bytes is changing the text encoding, or adding/removing the BOM from the front of the string? 

I'll double check the content size under Windows and Ubuntu and get back to you.

**Comment by tkelly42** [comment]
Hi,

Thanks for getting back.

I did quite a lot of checking on this as I thought it was something with my mime parser.

I copied the payload into fiddler and it “auto corrected” to 1084. If I manually set the value to 1072 in fiddler then the error reoccurred where the final mime boundary cuts off early.

I also copied and pasted into Notepad++ with CRLF symbols showing and confirmed 1084.

The windows test also sent the value as 1084 and when I ran it from a local Ubuntu box it also reported 1084.

[cid:image001.png@01D2B463.D7858720]
Notepad ++ shows 1084 in count

**Comment by rchadwic** [comment]
Actually, you're right - there is something going on here. I just ran this under Windows, and the number reported was 1084. I'm not sure where the additional bytes are coming from - probably padding or encoding. I no longer know which number is correct. Anyone else have any insight here?
```
POST /xapi/statements HTTP/1.1
Content-Type: multipart/mixed; boundary=-------314159265358979323846
X-Experience-API-Version: 1.0.3
Authorization: Basic dG9tOjEyMzQ=
host: lrs.adlnet.gov
content-length: 1084
Connection: close

---------314159265358979323846
Content-Type: application/json

{"actor":{"objectType":"Agent","mbox":"mailto:sample.agent@example.com","name":"Sample Agent"},"verb":{"id":"http://adlnet.gov/expapi/verbs/answered","display":{"en-US":"answered"}},"object":{"id":"http://www.example.com/tincan/activities/multipart","objectType":"Activity","definition":{"name":{"en-US":"Multi Part Activity"},"description":{"en-US":"Multi Part Activity Description"}}},"timestamp":"2014-07-11T13:51:03.971Z","attachments":[{"usageType":"http://example.com/attachment-usage/test","display":{"en-US":"A test attachment"},"contentType":"text/plain","length":27,"sha2":"495395e777cd98da653df9615d09c0fd6bb2f8d4788394cd53c56a3bfdcd848a","description":{"en-US":"A test attachment (description)"}}]}
---------314159265358979323846
Content-Disposition: attachment; filename="text_data.txt"
Content-Type: text/plain
Content-Transfer-Encoding: binary
X-Experience-API-Hash: 495395e777cd98da653df9615d09c0fd6bb2f8d4788394cd53c56a3bfdcd848a

here is a simple attachment
---------314159265358979323846--
```

**Comment by rchadwic** [comment]
Ok, I'm pretty sure this is related to line endings. I say that because there are 12 lines, and 12 additional bytes listed in the Windows version. 

I see that the file on disk under my Windows machine is today is 1084, yesterday on a different machine it was 1072. This is almost certainly related to the GIT configuration, which can sometimes swap /r for /r/n. You might want to look at your parsers though - I'll bet that the actual payload of the request is correct the stated length.

**Comment by tkelly42** [comment]
The XAPI Spec states CRLF for line ending and makes it clear not to forget them during parsing.  

RFC 2046 "4.1.1Representation of Line Breaks" states that line breaks MUST always be represented as CRLF.

So from what I can tell mime message should always use \r\n .

**Comment by rchadwic** [comment]
Yeah, you're correct. I think there is a configuration issue with your GIT setup that is causing this drama. Check out this documentation.

https://help.github.com/articles/dealing-with-line-endings/

**Comment by tkelly42** [comment]
Hi.  Just to be clear, I ONLY experience the issue when running the live LRS Test Suite.  The issue has never presented during local tests and I've tested under 64 bit windows  and 64 bit Ubuntu.

**Comment by rchadwic** [comment]
Ah thank you, I understand now. I'll check out live server GIT config.

**Comment by rchadwic** [comment]
So, a recent refactor might just make this a non-issue anyway. We've reworked the attachment test to dynamically compute some hashes and such, and are no longer reading the whole http post  body from a file anyway. Would you test this out on the staging branch of the test suite? That branch should solve this issue.

**Comment by tkelly42** [comment]
apologies for not getting back sooner. I can confirm that the issue is resolved with the latest test on live and I no longer have to account for missing characters at the end of boundaries

**Comment by rchadwic** [comment]
Nice! Glad to hear that worked out. There's a good lesson here for future reference, but it looks like it was sort of overcome by events anyway.
