### ISSUE TITLE
"Since" test doesn't appear to allow for any clock drift

### ISSUE THREAD

**Issue by bscSCORM** [adlnet/lrs-conformance-test-suite#190]
I don't see this on the same machine, but when running from one machine to another where the clock is slightly off (about 2 seconds) I'm seeing failures on the 3 variants of this test for the different document resources:

> An LRS's returned array of ids from a successful GET request to the (any) Resource all refer to documents stored after the TimeStamp in the "since" parameter of the GET request

Looking at the log of the requests sent, if the test allows for any clock drift between the test machine and the LRS, it's less than a second.

LRSs are not allowed to be "eventually consistent" here, however it doesn't seem reasonable for a client (or for tests) to assume that both the client machine and the LRS clocks are correct within 1 second. In order to allow real world implementations to consistently pass, I suggest these tests be written to allow the LRS and test machine clocks to be off by at least a full second either way, and even something like 5 seconds seems reasonable.

**Comment by cr8onski** [comment]
I agree, and I don't see it as a big problem to add that into the test suite.  Unless you or anyone else have any objections or concerns.  I'm going to proceed making that change (adding 5 seconds wiggle room) to since and until tests in the test suite.

**Comment by bscSCORM** [comment]
👍 fixed in https://github.com/adlnet/lrs-conformance-test-suite/commit/a6c64a013894ce928c5e5b98958395788cac6f6b
