### ISSUE TITLE
Apparently different attachment bytes depending on test platform

### ISSUE THREAD

**Issue by bscSCORM** [adlnet/lrs-conformance-test-suite#191]
I'm seeing some odd behavior in the test:

> should succeed when attachment is raw data and request content-type is "multipart/mixed"

When I run this test from a Windows 7 box, no problem. When I run it from OS X El Capitan, _against the same LRS_ , I get a hash mismatch.

Digging further, the LRS logs show an extra `c2` (hex) in the binary portion of the stream it received. That isn't the only difference (note how the lines are out of sync already), but it was just easy to locate being next to a "roRO" (ASCII) sequence.

The extra `c2` doesn't appear in the test log in either case, so if there is actual different behavior between the tests (which seems likely), it's unfortunately probably happening within a library. I wouldn't have suggested this might be a test issue except for the different behavior running the same version of the tests via Windows or OSX.

I haven't tried this with the hosted version of the tests yet because I don't have an externally accessible system with our latest code on it.

Due to this observed difference, I ask that ADL verify the output of the hosted version of the test in particular, that is receive the bytes the test is sending out, save them to a file, hash them and compare the hashes. Maybe that can be done using the ADL LRS?

If that can't be done quickly,  I suggest turning this test off until it can be done. We've gone back and forth on this test a bit, it's clearly important to test because it seems tricky to get right, but since the test itself also is tricky to get right, let's take some more time to test the test.

Below is 'xxd' output where I saw a difference:

```
0000270: 4a50 0000 001a 0000 0388 726f 524f 0000  JP........roRO..
```
vs
```
0000280: 0372 6a61 4a50 0000 001a 0000 03c2 8872  .rjaJP.........r
0000290: 6f52 4f00 0000 2400 0003 c2a2 656c 4752  oRO...$.....elGR
```

**Comment by ljwolford** [comment]
Hi Ben,

So I ran this test on Ubuntu (14.04) and OSX (El Capitan 10.11.6) against the same LRS and at all times the hash of the binary before being send and after was `6db5ef79a2200f02fe4993595f6132cca8ce36224d08d670193b50be989e6588`.

I also ran the hosted test suite against the ADL LRS and got the same result. I quickly checked the binary file from the output and saw it had the extra `c2` like in your second example. Could this be related in any way to #189 ?

**Comment by bscSCORM** [comment]
I'm not sure because it actually works on Windows for me. #189 does sound very much like a git settings issue. For that issue, perhaps the test should verify the hash before sending the file and just error out with "this file was checked out improperly" if the source file hash doesn't match.

Note that the hash of the test file stays correct for me, it seems like the extra `c2` is getting added somewhere in transit. Which I think tracks with what you're saying that you see the extra `c2` "in the output", that is the file that the LRS has saved, right?

**Comment by ljwolford** [comment]
OK I see what you're saying now. I think the encoding is wrong when reading the attachment. There will be a patch out for it later to try and test. The `binary` encoding being used is adding the `c2`. I changed it to `hex` and it matches my xxd output.

**Comment by bscSCORM** [comment]
@ljwolford great, I should be able to test it quickly once it's out, thanks!

**Comment by ljwolford** [comment]
@bscSCORM i went through and refactored some of the other attachment tests...hopefully they are acting normally now. let me know your results. thanks!

**Comment by bscSCORM** [comment]
@ljwolford looks like that fixes this issue, something you changed managed to cause us to `500` on
> should fail when attachments missing header "X-Experience-API-Hash"
but that's on us.

**Comment by bscSCORM** [comment]
@ljwolford you might be interested to know about this change in the

> should fail when attachments missing header "X-Experience-API-Hash"

Test... previously it sent an attachment that was just missing the header, eg:

```
---------314159265358979323846
Content-Disposition: attachment; filename="text_data.txt"
Content-Type: text/plain
Content-Transfer-Encoding: binary

here is a simple attachment
```

Now it's also missing the CRLF between the last header and the attachment:

```
---------314159265358979323846
Content-Type: text/plain
Content-Transfer-Encoding: binary
here is a simple attachment
```

In both cases the result should be `400`, these are both good tests, but you might want to test both conditions separately and call out "missing CRLF" as its own test case.

**Comment by ljwolford** [comment]
Good catch. I think that was just a copy/past drop. I'll add it back in.
