### ISSUE TITLE
Consistent-Through ignored for attachment retreival, spec question

### ISSUE THREAD

**Issue by bscSCORM** [adlnet/lrs-conformance-test-suite#207]
I suggest this should be reviewed on all the attachment tests, but here is one case in particular.

Running the test: `should process using GET with "attachments"`

Will always result in:

`Error: Expected response status code to be 200 got 404`

When the LRS is not ready with the statement and attachment being requested, and temporarily returns `404` and a consistent-through of before the statement with the attachment was stored.

Even when the last request sent has a timestamp of `date: Fri, 07 Jul 2017 21:32:26 GMT`
And the `404` response it receives has the header:
`x-experience-api-consistent-through: 2017-07-07T21:32:23.652Z`

(Note that HTTP header names are case-insensitive, according to RFC 2616)

Now, what appears to be going on is the tests are seeing that the requested _statement_ is there, and then turning around and requesting the attachment. The LRS _has_ stored the statement, and will return it, but does not yet have the attachment available (because the attachment storage used becomes consistent more slowly than the storage used for statements). It returns `404` for the request that asks for the attachment, and a consistent-through date reflecting it's not yet completely consistent through the time the statement with the attachment was stored.

So there is an interesting spec question here about how "all Statements" and "reasonably certain" and "SHOULD account for any temporary condition" interact:
```
The LRS MUST include the header "X-Experience-API-Consistent-Through", in ISO 8601 combined date and time format, on all responses to Statements Resource requests, with a value of the timestamp for which all Statements that have or will have a "stored" property before that time are known with reasonable certainty to be available for retrieval. This time SHOULD take into account any temporary condition, such as excessive load, which might cause a delay in Statements becoming available for retrieval. It is expected that this will be a recent timestamp, even if there are no recently received Statements.
```

I'll admit we're stretching the spec here a bit by returning a different consistent through header when we find out the attachment isn't available yet than we would otherwise, but there appears to be a little wiggle room in the spec, and this seems like a really reasonable thing for an LRS to do (vs having a longer consistent-through buffer that allows for less frequent attachment requests). "This particular request is going to have a consistency issue" seems like a sort of "temporary condition" that it's better for clients if the LRS takes into account.

So, two questions here:
* should the test changes to accept this sort of LRS behavior?
* should the spec change to clarify whether this behavior conforms or does not?

```
REQUEST SUPERREQUEST
_______________________________________
GET /ScormEngineInterface/TCAPI/default/statements?statementId=3f3c77da-f538-4ceb-9347-cb2842d05657 HTTP/1.1
X-Experience-API-Version: 1.0.3
Authorization: Basic c2Nvcm06c2Nvcm0yMDA0
host: localhost:64619
Connection: close

RESPONSE SUPERREQUEST
_______________________________________
HTTP/1.1 200 OK
server: ASP.NET Development Server/11.0.0.0
date: Fri, 07 Jul 2017 21:32:26 GMT
x-experience-api-version: 1.0.3
access-control-allow-origin: *
access-control-allow-methods: HEAD,GET,POST,PUT,DELETE
access-control-allow-headers: Content-Type,Content-Length,Authorization,If-Match,If-None-Match,X-Experience-API-Version,X-Experience-API-Consistent-Through
access-control-expose-headers: ETag,Last-Modified,Cache-Control,Content-Type,Content-Length,WWW-Authenticate,X-Experience-API-Version,X-Experience-API-Consistent-Through
x-experience-api-consistent-through: 2017-07-07T21:32:26.009Z
transfer-encoding: chunked
cache-control: private
content-type: application/json; charset=UTF-8
connection: Close

{"version":"1.0.0","attachments":[{"usageType":"http://example.com/attachment-usage/test","display":{"en-US":"A test attachment"},"description":{"en-US":"A test attachment (description)"},"contentType":"text/plain","length":27,"sha2":"495395e777cd98da653df9615d09c0fd6bb2f8d4788394cd53c56a3bfdcd848a"},{"usageType":"http://example.com/attachment-usage/test","display":{"en-US":"A test attachment"},"description":{"en-US":"A test attachment (description)"},"contentType":"text/plain","length":33,"sha2":"7063d0a4cfa93373753ad2f5a6ffcf684559fb1df3c2f0473a14ece7d4edb06a"}],"id":"3f3c77da-f538-4ceb-9347-cb2842d05657","actor":{"objectType":"Agent","name":"xAPI account","mbox":"mailto:xapi@adlnet.gov"},"verb":{"id":"http://adlnet.gov/expapi/verbs/attended","display":{"en-GB":"attended","en-US":"attended"}},"object":{"objectType":"Activity","id":"http://www.example.com/meetings/occurances/34534"},"timestamp":"2017-07-07T21:32:26.152Z","stored":"2017-07-07T21:32:26.152Z","authority":{"objectType":"Agent","account":{"homePage":"http://example.org/bsc","name":"scorm"}}}
=======================================
REQUEST SUPERREQUEST
_______________________________________
GET /ScormEngineInterface/TCAPI/default/statements?attachments=true&statementId=3f3c77da-f538-4ceb-9347-cb2842d05657 HTTP/1.1
X-Experience-API-Version: 1.0.3
Authorization: Basic c2Nvcm06c2Nvcm0yMDA0
host: localhost:64619
Connection: close

RESPONSE SUPERREQUEST
_______________________________________
HTTP/1.1 404 Not Found
server: ASP.NET Development Server/11.0.0.0
date: Fri, 07 Jul 2017 21:32:26 GMT
x-experience-api-version: 1.0.3
access-control-allow-origin: *
access-control-allow-methods: HEAD,GET,POST,PUT,DELETE
access-control-allow-headers: Content-Type,Content-Length,Authorization,If-Match,If-None-Match,X-Experience-API-Version,X-Experience-API-Consistent-Through
access-control-expose-headers: ETag,Last-Modified,Cache-Control,Content-Type,Content-Length,WWW-Authenticate,X-Experience-API-Version,X-Experience-API-Consistent-Through
x-experience-api-consistent-through: 2017-07-07T21:32:23.652Z
cache-control: private
content-type: text/html
connection: Close

Statement found, but associated attachment information was not: 3f3c77da-f538-4ceb-9347-cb2842d05657
=======================================
```

**Comment by garemoko** [comment]
My initial reaction to this is it sounds like something that needs to be considered at spec level and therefore perhaps not testing this is the right approach. I would like to understand more what "not testing this" looks like though - clearly we do need tests around attachments.

**Comment by bscSCORM** [comment]
@garemoko I agree, the spec should get more specific about consistent through here.

So, I think "not testing it" in this case would mean the current test would need to accept a `404` when requesting attachments, and delay and try again. I think the test is making the assumption that if a statement has previously been returned, then that statement is consistent, including its attachments and it should be fine to grab the attachments. I can certainly see rationale for making that assumption, but "reasonably certain" and "temporary condition" make me question it.

So I'd suggest that we not test this by having the test suite back off and retry based on the consistent through time reported for any request that returns a `404` or is missing something the test suite expects, even if items returned on a prior request imply the later request should not `404` or have missing items.

If we want to have a test for: "once a consistent through header has been sent, don't return an earlier consistent through time" or: "once a statement has been returned in a response, it can't be left out of a future response with an appropriate consistent-through header even if different details are requested (eg: canonical or attachments included)" I suggest that those should be specific tests, and not assumptions included in other tests, and also we should have a spec discussion before adding those specific tests.

**Comment by garemoko** [comment]
Thanks, that's helpful. 

Thinking some more on this issue, the big concern is "will this behavior break statement forwarding?" where some LRS is pulling from another and relying on the `x-experience-api-consistent-through` header. That's the scenario that the header is designed to support. 

I think the answer is "no it won't break statement forwarding" because I can't imagine that an LRS polling another for this purpose would use different query parameters in its requests. On that basis, I think it's OK for an LRS to return inconsistent `x-experience-api-consistent-through` header values based on different query parameters, such as `attachments`. 

In fact, I could argue that the `x-experience-api-consistent-through` header is a statement about the current response rather than the state of the LRS and therefore, so long as it was accurate it'd be OK for an LRS to return a slightly earlier `x-experience-api-consistent-through` header in the 2nd of two identical requests in series. I could see this maybe happening in some load balanced set up, for example.

**Comment by bscSCORM** [comment]
@garemoko having thought about this distinction now:
>  I could argue that the x-experience-api-consistent-through header is a statement about the current response rather than the state of the LRS

I think we can make a pretty strong case that the `x-experience-api-consistent-through` can be most useful if it's about the current response. 

> the timestamp for which all Statements that have or will have a "stored" property before that time

is a pretty strong indication in the other direction (state of the LRS) in the spec, but I think "reasonably certain" and "temporary condition" might give us enough stretch to use "current response".

So what I'd hope to do if we can agree on it is to plan on clarifying the spec in the other direction in a `minor` update (real clients shouldn't be relying on "state of the LRS" interpretation), and ensuring tests allow this interpretation for 1.0.

**Comment by garemoko** [comment]
👍
