### ISSUE TITLE
Console runner should provide non-zero exit code for failures

### ISSUE THREAD

**Issue by ryansmith94** [adlnet/lrs-conformance-test-suite#221]
**Version**
Master branch at commit 3a04557d73173e50ae55fb37a5aa4e68fad924d2

**Steps to reproduce the issue**
1. Run the tests with invalid auth details.

**Expected behaviour**
The runner should exit with a non-zero exit code so that CI tools show a failed build.

**Actual behaviour**
The runner exits with a zero exit code.

**Comment by vbhayden** [comment]
Did the merge add the functionality requested with this issue?

**Comment by ryansmith94** [comment]
No the PR that was merged into LearningLocker's xAPI service didn't fix the issue here.

**Comment by ryansmith94** [comment]
The open PR should fix the issue.
