### ISSUE TITLE
`npm install` requires git binary

### ISSUE THREAD

**Issue by samcayford** [adlnet/lrs-conformance-test-suite#233]
Can you remove the need to have the git binary in the path in order to run this test suite?

We run our tests in docker containers, we have no need or want to install git inside them, and in fact it it's quite a pain for windows.

Can we make the 2 modules being pulled from a person's fork into legit modules? Or remove the need to use forked modules that haven't been made into real modules?

**Comment by vbhayden** [comment]
Since you're using docker, you should be able to run `npm install` from the host and copy the node_modules directory into the container via the Dockerfile.  Am i misunderstanding your problem ?

**Comment by samcayford** [comment]
The host doesn't have git, node or npm either and has no need for them.

Why does a node project have a dependency on having git in the system's path? That's not very node-y

**Comment by vbhayden** [comment]
Will look at this today.

**Comment by vbhayden** [comment]
I'm not sure why those 2 are uniquely pulled from git, but I'll get a branch and pr out for this by cob today.

**Comment by vbhayden** [comment]
@samcayford are you able to check the pr'd branch and see if your docker containers can install dependencies without git?

**Comment by samcayford** [comment]
@vbhayden yep, looks good now. If i'd known it was that simple i could have done it, i just assumed you required something from those particular branches.

Thanks

**Comment by vbhayden** [comment]
Looking through now to see if there are any issues with using the public npm version, will merge if not.

**Comment by vbhayden** [comment]
There were a few small differences between the versions being pulled and the npm-standard versions.  For safety, they modified versions have been added locally.  If the current branch's local system works for you @samcayford  then we'll go ahead and merge it.

**Comment by samcayford** [comment]
Yep, still works with local versions 👍
