### ISSUE TITLE
Receiving the following message when attempting to complete activity in moodle. 

### ISSUE THREAD

**Issue by jlevellhall** [adlnet/lrs-conformance-test-suite#250]
Error attempting to get registration data from State API.

object(TinCan\LRSResponse)#118 (3) {
  ["success"]=>
  bool(false)
  ["content"]=>
  string(1197) "Request failed: ErrorException: fopen(http://learn.monoceros.icu/data/xAPI/activities/state?activityId=http%3A%2F%2FJvHZd3VDgaFKCvTW1fZVDS-nsPxIUmpZ_rise&agent=%7B%22objectType%22%3A%22Agent%22%2C%22name%22%3A%22Jeremy%20Hall%22%2C%22mbox%22%3A%22mailto%3Ajeremy.hall%40digicert.com%22%7D&stateId=http%3A%2F%2Ftincanapi.co.uk%2Fstateapikeys%2Fregistrations): failed to open stream: Connection timed out in /var/www/moodle-1click/mod/tincanlaunch/TinCanPHP/src/RemoteLRS.php:150
Stack trace:
#0 [internal function]: TinCan\RemoteLRS->TinCan\{closure}(2, 'fopen(http://le...', '/var/www/moodle...', 150, Array)
#1 /var/www/moodle-1click/mod/tincanlaunch/TinCanPHP/src/RemoteLRS.php(150): fopen('http://learn.mo...', 'rb', false, Resource id #240)
#2 /var/www/moodle-1click/mod/tincanlaunch/TinCanPHP/src/RemoteLRS.php(669): TinCan\RemoteLRS->sendRequest('GET', 'activities/stat...', Array)
#3 /var/www/moodle-1click/mod/tincanlaunch/locallib.php(379): TinCan\RemoteLRS->retrieveState(Object(TinCan\Activity), Object(TinCan\Agent), 'http://tincanap...')
#4 /var/www/moodle-1click/mod/tincanlaunch/view.php(106): tincanlaunch_get_global_parameters_and_get_state('http://tincanap...')
#5 {main}"
  ["httpResponse"]=>
  NULL
}

**Comment by vbhayden** [comment]
Morning @jlevellhall, this might not be the right repository for that?  This is the codebase for the LRS conformance suite, a test battery designed for checking an LRS's conformance to various versions of the xAPI spec.

It sounds like you have an issue with an old TinCan Moodle plugin, which might be over at: https://github.com/davidpesce/moodle-mod_tincanlaunch

Best of luck 🙂
