### ISSUE TITLE
[2.0.0]Timestamp UTC conversion test uses an invalid timestamp

### ISSUE THREAD

**Issue by integralla** [adlnet/lrs-conformance-test-suite#261]
The "checks if the LRS converts timestamps to UTC" test found in test/v2_0/4.2.7-Additional-Requirements-for-Data-Types.js posts a statement with a timestamp that does not conform to RFC 3339 "date-time" format as documented at https://datatracker.ietf.org/doc/html/rfc3339#section-5.6.

Specifically, the time value does not include seconds:

```javascript
const dateEST = "2023-05-04T12:00-05:00";
```

Per the RFC 3339 "date-time" format, seconds are required:

```
date-fullyear   = 4DIGIT
date-month      = 2DIGIT  ; 01-12
date-mday       = 2DIGIT  ; 01-28, 01-29, 01-30, 01-31 based on
                             ; month/year
time-hour       = 2DIGIT  ; 00-23
time-minute     = 2DIGIT  ; 00-59
time-second     = 2DIGIT  ; 00-58, 00-59, 00-60 based on leap second
                             ; rules
time-secfrac    = "." 1*DIGIT
time-numoffset  = ("+" / "-") time-hour ":" time-minute
time-offset     = "Z" / time-numoffset

partial-time    = time-hour ":" time-minute ":" time-second
                     [time-secfrac]
full-date       = date-fullyear "-" date-month "-" date-mday
full-time       = partial-time time-offset

date-time       = full-date "T" full-time
```

This test is failing for an LRS that validates the timestamp property against this ISO 8601 profile (for example, using the [JSON schema `date-time` format](https://json-schema.org/understanding-json-schema/reference/string#dates-and-times) and/or other means.)

**Comment by vbhayden** [comment]
This looks minor enough that we can go ahead and update it, since it'd still satisfy both ISO 8601 and RFC 3339.

Ideally, the IEEE documentation would be a bit clearer about what an LRS is expected to accept for the timestamp format.  Currently, we had to draw from the LRP section and its guidance on RFC 3339 + ISO 8601 needing to both be satisfied.

Thanks for the update!
