### ISSUE TITLE
[2.0.0] Concurrency > 409 Conflict response tests fail if the error response is JSON, rather than a string

### ISSUE THREAD

**Issue by integralla** [adlnet/lrs-conformance-test-suite#266]
The concurrency tests found in test/v2_0/4.1.4-Concurrency.js include tests to ensure that a 409 Conflict response is returned in the case that a PUT request is received for an existing document but without a header precondition. One of the tests ensures that an explanation of the error is provided in the response, but it expects the type to be a string and incorrectly rejects a error response that wrapped in a JSON object.

```javascript
expect(responseText).is.a("string").with.length.greaterThan(0);
```

The tests for xAPI 1.0 just ensure the response text has a length greater than zero which may be appropriate here. Otherwise, it should also accept a non empty object.

**Comment by vbhayden** [comment]
The `.to.not.be.empty` use makes sense, although that requirement really seems to be expecting a plaintext sentence explaining the issue etc:

> *shall* return a response explaining that the Learning Record Provider *should* ...

Just added that in, will check it on staging today before updating the live service.
