### ISSUE TITLE
[2.0.0] "Duplicate Endpoint Joining in 'getStatementExactPromise' Method

### ISSUE THREAD

**Issue by tech-getsmart** [adlnet/lrs-conformance-test-suite#268]
In test/4.1.6.1-Statement-Resource.js, [Communication/timestamps 2.4.7 GET Statements] Part use 'getStatementExactPromise' method to get returns. 

But that request has duplicated endpoint, like this : [http://localhost:8080/xapi/http://localhost:8080/xapi/statements]

I think, this is because in 'getStatementExactPromise' method, it join paths as endpoint, and 'getDocuments' join paths again.

**Comment by vbhayden** [comment]
The live one has been updated, please run your test again -- very sorry for the inconvenience.

I didn't realize that the function in question was only used at that one place, and it still isn't clear why other LRS's (from simple ones like ours to advanced vendor solutions) seemed fine with that clear oversight, but thank you for reporting the issue to us!
