### ISSUE TITLE
ETag validation question

### ISSUE THREAD

**Issue by raif-s-naffah** [adlnet/lrs-conformance-test-suite#275]
hi there,

when running V2_0 conformance tests, i see some failures for tests like _"When responding to a GET Request the Etag header must be enclosed in quotes"_.

looking at the code that is likely to be the cause for this i note the following in 14.1.4-Concurrency.js`:

```javascript
it('When responding to a GET Request the Etag header must be enclosed in quotes', async() => {
    let documentResponse = await xapiRequests.getDocuments(resourcePath, resourceParams);
    let etag = documentResponse.headers.etag;
    expect(etag).to.be.a("string");
    if (etag[0] !== '"') {
        expect(etag[0]).to.equal('W');
        expect(etag[1]).to.equal('/');
        etag = str.substring(2)
    }
    expect(etag[0]).to.equal('"');
    expect(etag[41]).to.equal('"');
});
```
which if i'm not mistaken is expecting an ETag value 42-characters long.  this figure of 42 characters, including the surrounding double-quotes implies (probably) the use of a hash algorithm that generates a 160-bit output; e.g. SHA-1.

[RFC 7232][1], cited by [RFC 7231][2] does not mandate the use of a specific algorithm for generating this opaque value.

the [2.0 specs for the LRS][3] similarly do not mandate any algorithm for generating ETags.

my question is , is there some xAPI normative text that mandates a specific way for generating ETags.  if yes, would appreciate a link or pointer.  otherwise may be amend the test(s) appropriately.

thanks + cheers;

[1]: https://datatracker.ietf.org/doc/html/rfc7232#section-2.3
[2]: https://datatracker.ietf.org/doc/html/rfc7231#section-7.2
[3]: https://opensource.ieee.org/xapi/xapi-base-standard-documentation/-/blob/main/9274.1.1%20xAPI%20Base%20Standard%20for%20LRSs.md

**Comment by vbhayden** [comment]
Hmmm, so I am actually not sure.  This line of code predated me, and I just carried it over to the 2.0 tests without much thought.  We can maybe adjust this to account for a variable length, but I'll check with our specs + standards guy today.

**Comment by vbhayden** [comment]
morning @raif-s-naffah,

The CTS has been updated to remove the 40-character expectation and now just requires any string value between quotes. 

https://github.com/adlnet/lrs-conformance-test-suite/commit/2ec25f2eb8ccfcb7cb63ec2679dbd965f9f6ffdc

Thanks for bringing this up.

**Comment by raif-s-naffah** [comment]
hi @vbhayden,

just updated my local copy of the CTS and verfified that your fix indeed works as expected.

thanks + cheers;
rsn
