### ISSUE TITLE
V2.0 Statement `canonical` format test 

### ISSUE THREAD

**Issue by raif-s-naffah** [adlnet/lrs-conformance-test-suite#276]
hi there,

while running conformance tests for the v2_0 version, few validation tests are failing b/c they are assuming a _Statement_ returned by a **`GET`** will *always* contain an array of _Activity_ objects for the `category` property of the statement's `contextActivities` property w/in the `context` property.

the code in question seems to be the following starting at line 1083 in `4.1.6.1-Statement-Resource.js`:
```javascript
expect(statement.context.contextActivities.category[0].definition.description).not.to.have.property("en-US");
expect(statement.context.contextActivities.category[0].definition.name).not.to.have.property("en-US");
```
the error message as it appears in the log is:
```
"error": "TypeError: Cannot read properties of undefined (reading 'definition')"
```
the JSON representation of the _Statement_ causing the error is:
```json
{\"id\":\"01928d4f-487c-7a72-a38b-f5097c07d203\",\"actor\":{\"objectType\":\"Agent\",\"name\":\"xAPI account\",\"mbox\":\"mailto:xapi@adlnet.gov\"},\"verb\":{\"id\":\"http://adlnet.gov/expapi/verbs/attended\",\"display\":{\"en-GB\":\"attended\"}},\"object\":{\"id\":\"http://www.example.com/meetings/occurances/34534\"},\"context\":{\"registration\":\"ec531277-b57b-4c15-8d91-d292c5b2b8f7\",\"instructor\":{\"objectType\":\"Agent\",\"name\":\"xAPI mbox\",\"mbox\":\"mailto:pri@adlnet.gov\"},\"contextActivities\":{\"category\":{\"id\":\"http://www.example.com/test/array/statements/pri\",\"definition\":{\"name\":{\"en-GB\":\"example meeting\"},\"description\":{\"en-GB\":\"An example meeting that happened on a specific occasion with certain people present.\"},\"moreInfo\":\"http://virtualmeeting.example.com/345256\",\"extensions\":{\"http://example.com/profiles/meetings/extension/location\":\"X:\\\\meetings\\\\minutes\\\\examplemeeting.one\",\"http://example.com/profiles/meetings/extension/reporter\":{\"id\":\"http://openid.com/342\",\"name\":\"Thomas\"}}}}},\"platform\":\"Example virtual meeting software\",\"language\":\"tlh\",\"statement\":{\"objectType\":\"StatementRef\",\"id\":\"6690e6c9-3ef0-4ed3-8b37-7f3964730bee\"},\"extensions\":{}},\"timestamp\":\"2024-10-14T23:13:56+00:00\",\"stored\":\"2024-10-14T23:13:56+00:00\",\"authority\":{\"objectType\":\"Agent\",\"mbox\":\"mailto:unverified@inter.net\"}}
```

indeed a quick check using a browser debugger after parsing the above as `statement`,  trying to access the same path as `statement.context.contextActivities.category[0].definition.name` causes `Uncaught TypeError: statement.context.contextActivities.category[0] is undefined`. 

accessing `statement.context.contextActivities.category.definition.name` on the other hand works as expected, resulting in `Object { "en-GB": "example meeting" }`.

the V2.0 specs [4.2.2.5 Context][1] describe `contextActivities` as...
> A map of the types of learning activity context that this Statement is related to. Every key in the contextActivities Object shall be one of "parent", "grouping", "category", or "other". Every value in the contextActivities Object shall be either a single Activity Object or an array of Activity Objects.

which seems to contradict the expectations of the test.

would appreciate it if somebody can point me to the text that backs the assumptions of the test.

[1]: https://opensource.ieee.org/xapi/xapi-base-standard-documentation/-/blob/main/9274.1.1%20xAPI%20Base%20Standard%20for%20LRSs.md#4225-context

thanks in anticipation + cheers;
rsn

**Comment by vbhayden** [comment]
Morning @raif-s-naffah,

So this test makes that assumption based on the statement sent just before, which uses the template:

```
{
  "registration": "ec531277-b57b-4c15-8d91-d292c5b2b8f7",
  "platform": "Example virtual meeting software",
  "language": "tlh",
  "statement": {
    "objectType": "StatementRef",
    "id": "6690e6c9-3ef0-4ed3-8b37-7f3964730bee"
  },
  "contextActivities": {
    "category": {
      "objectType": "Activity",
      "id": "http://www.example.com/meetings/occurances/34534",
      "definition": {
        "name": {
          "en-GB": "example meeting",
          "en-US": "example meeting"
        },
        "description": {
          "en-GB": "An example meeting that happened on a specific occasion with certain people present.",
          "en-US": "An example meeting that happened on a specific occasion with certain people present."
        },
        "moreInfo": "http://virtualmeeting.example.com/345256",
        "extensions": {
          "http://example.com/profiles/meetings/extension/location": "X:\\meetings\\minutes\\examplemeeting.one",
          "http://example.com/profiles/meetings/extension/reporter": {
            "name": "Thomas",
            "id": "http://openid.com/342"
          }
        }
      }
    }
  }
}
```
and the dot path should be fine as a result etc.  The `contextActivities` can have other forms, but this test isn't checking for all forms -- just the one provided in the statement it sends beforehand.

**Comment by raif-s-naffah** [comment]
hi @vbhayden 

i'm not sure i understand your comment.

the issue i'm raising is related to the fact that the contents of the `category` property is a simple _Activity_ and not an array of activities.  the specs as i understand them allow for this and the implementation handled it when ingesting the **`POST`** data.

the code of the test succeeds if the specs mandated a generated _Statement_ w/ a `category` (and other `contextActivities`) property MUST be an array even when only one _Activity_ is included.  again to my understanding that is NOT what the specs state.

IMHO a more accurate check would be to either use the form w/o the array index reference, or re-write to handle the general case (of may be other implementtions returning an array of 1 element) as in (very roughly like)...
```
let cat = statement.context?.contextActivities?.category;
if (Array.isArray(cat)) {
    // expect using cat[0].definition
} else {
    // expect using cat.definition
}
```

hope this makes sense + cheers;
rsn

**Comment by vbhayden** [comment]
@raif-s-naffah ok I am seeing your point.  That template definitely does have a single object and not an array, so this was a bit confusing to me.

There's a line in the IEEE docs stating:
> The LRS shall return every value in the contextActivities Object as an array, even if it arrived as a single Activity Object.
https://opensource.ieee.org/xapi/xapi-base-standard-documentation/-/blob/main/9274.1.1%20xAPI%20Base%20Standard%20for%20LRSs.md#4242-specific-statement-data-requirements-for-an-lrs

So this might be why the test expects an array for that object.

**Comment by raif-s-naffah** [comment]
noted + thanks.

closing - works as expected.
