### ISSUE TITLE
V2.0 GET Statement w/ attachment

### ISSUE THREAD

**Issue by raif-s-naffah** [adlnet/lrs-conformance-test-suite#277]
hi there,

one of the V2_0 conformance tests 4.1.6.1-Statement-Resource.js lines 2635..2663) `POST`s a `mutipart/mixed` message w/ 1 _Statement_ containing the following `attachments` property in the 1<sup>st</sup> part:
```
[{ "usageType":"http://example.com/attachment-usage/test",
  "display":{"en-US":"A test attachment"},
  "description":{"en-US":"A test attachment (description)"},
  "contentType":"text/plain",
  "length":27,
  "sha2":"495395e777cd98da653df9615d09c0fd6bb2f8d4788394cd53c56a3bfdcd848a",
  "fileUrl":"http://over.there.com/file.txt"}]
```
the 2<sup>nd</sup> part is a text that has an `X-Experience-API-Hash` value matching the one specified in the sole _Attachment_ of the previous statement.

to my understanding --confirmed [here][1]-- the contents of an _Attachment_ w/ a valid `fileUrl` does not need to be stored in the LRS. 

the test however follows the `POST` w/ a `GET /statements?statementId=01928d4f-4e4a-7171-bb6c-fd10b928640d&attachments=true` and, if i haven't misunderstood the code, expects the response to contain the text originally sent.

would appreciate it if somebody can clarify how an LRS should deal w/ Attachments that have an external `fileUrl`.

thanks in anticipation + cheers;
rsn

[1]: https://opensource.ieee.org/xapi/xapi-base-standard-examples/-/issues/3

**Comment by vbhayden** [comment]
Morning @raif-s-naffah,

I might not be understanding the question well enough, but the actual path specified in `fileUrl` doesn't seem to matter for the attachment tests.  The signature does matter, but there isn't any consideration for an "external" address from what I can tell.

What issues are you bumping into with this tests?

**Comment by raif-s-naffah** [comment]
Hi @vbhayden,

Pls. bear w/ me here since this is a part of the specs i'm still struggling w/ (as demonstrated in #272). Hopefully w/ your input i will see the light :)

The test is sending...

1. A `multipart/mixed` **`POST`** w/ 2 parts like so...
```
POST /statements HTTP/1.1
Content-Type: multipart/mixed; boundary=-------314159265358979323846
X-Experience-API-Version: 2.0.0
host: localhost:9000
content-length: 925
Connection: keep-alive

---------314159265358979323846
Content-Type: application/json

{"actor":{"objectType":"Agent","name":"xAPI account","mbox":"mailto:xapi@adlnet.gov"},"verb":{"id":"http://adlnet.gov/expapi/verbs/attended","display":{"en-GB":"attended","en-US":"attended"}},"object":{"objectType":"Activity","id":"http://www.example.com/meetings/occurances/34534"},"attachments":[
{
  "usageType":"http://example.com/attachment-usage/test",
  "display":{"en-US":"A test attachment"},
  "description":{"en-US":"A test attachment (description)"},
  "contentType":"text/plain",
  "length":27,
  "sha2":"495395e777cd98da653df9615d09c0fd6bb2f8d4788394cd53c56a3bfdcd848a",
  "fileUrl":"http://over.there.com/file.txt"
}]}
---------314159265358979323846
Content-Type: text/plain
Content-Transfer-Encoding: binary
X-Experience-API-Hash: 495395e777cd98da653df9615d09c0fd6bb2f8d4788394cd53c56a3bfdcd848a

here is a simple attachment
---------314159265358979323846--
```

2. Followed by a **`GET`** w/ the following query string `/statements?statementId=01928d4f-4e4a-7171-bb6c-fd10b928640d&attachments=true`. the UUID here being the same returned in the response to the previous **`POST`**.
The result is a `multipart/mixed` response w/ just 1 part being a _Statement_ equivalent to the original one submitted in the **`POST`** like so:
```
HTTP/1.1 200 OK
content-type: multipart/mixed; boundary=6s4LOG2rjj9IoiD
server: LaRS
x-content-type-options: nosniff
permissions-policy: interest-cohort=()
x-frame-options: SAMEORIGIN
x-experience-api-version: 2.0.0
x-experience-api-consistent-through: 2024-10-14T23:13:57.888792892+00:00
transfer-encoding: chunked
date: Mon, 14 Oct 2024 23:13:57 GMT


--6s4LOG2rjj9IoiD
Content-Type: application/json
X-Experience-API-Consistent-Through: 2024-10-14T23:13:57.838346+00:00

{"id":"01928d4f-4e4a-7171-bb6c-fd10b928640d","actor":{"objectType":"Agent","name":"xAPI account","mbox":"mailto:xapi@adlnet.gov"},"verb":{"id":"http://adlnet.gov/expapi/verbs/attended","display":{"ar-EG":"حضر","en":"attended","en-GB":"attended","en-US":"attended","hy-AM":"ներկա է գտնվել","is-IS":"sótti","ja-JP":"出席した","kn-IN":"ಹಾಜರಿದ್ದರು","ko-KR":"참석","pa-IN":"ਹਾਜ਼ਰ","ru-RU":"участие","sk-SK":"zúčastnil"}},"object":{"id":"http://www.example.com/meetings/occurances/34534"},"timestamp":"2024-10-14T23:13:57+00:00","stored":"2024-10-14T23:13:57+00:00","authority":{"objectType":"Agent","mbox":"mailto:unverified@inter.net"},"attachments":[
{
  "usageType":"http://example.com/attachment-usage/test",
  "display":{"en-US":"A test attachment"},
  "description":{"en-US":"A test attachment (description)"},
  "contentType":"text/plain",
  "length":27,
  "sha2":"495395e777cd98da653df9615d09c0fd6bb2f8d4788394cd53c56a3bfdcd848a",
  "fileUrl":"http://over.there.com/file.txt"
}]}
--6s4LOG2rjj9IoiD--
```

Pls. note i reformatted the `attachments` property to make it clearer the _Statement_ only references 1 _Attachment_. That single _Attachment_ has a populated `fileUrl` referencing contents external to the LRS being tested.

The test then fails w/ the following error message: _"AssertionError: expected -1 to not deeply equal -1"_.

May be i misinterpreted the error message but i was expecting one of two things:

1. The **`POST`** should fail but did not.  it should've failed b/c it contained excess parts  i.e. one binary part that should not be matched to an _Attachment_ entry given that the single _Attachment_ has a populated `fileUrl`.

2. The **`GET`** should succeed b/c the LRS is not hosting the contents of the _Attachment_'s binary --it's externally available at the specified `fileUrl` even though the response came back as a `multipart/mixed` and not `application/json`.

my question is why the **`GET`** is failing?

**Comment by raif-s-naffah** [comment]
never mind.

the section [here][1] contains this...
> When receiving a PUT or POST with a document type of multipart/mixed, an LRS shall reject batches of Statements having Attachments that neither contain a fileUrl nor match a received Attachment part based on their hash.

which explains what the expected behaviour is.

apologies for the noise.

closing - works as expected.

[1]: https://opensource.ieee.org/xapi/xapi-base-standard-documentation/-/blob/main/9274.1.1%20xAPI%20Base%20Standard%20for%20LRSs.md#lrs-requirements
