### ISSUE TITLE
V2.0 Empty `relevantTypes` w/ Context Agents and Groups

### ISSUE THREAD

**Issue by raif-s-naffah** [adlnet/lrs-conformance-test-suite#279]
hi there,

the v2.0.0 specs [here][1] under [4.2.2.5 Context][2] state that the `relevantTypes` property for both *Context Agent* and *Context Group* is

* optional, and
* a collection of 1 or more Relevant Type(s) used to characterize the relationship between the Statement and the actor. **If not provided**, only a generic relationship is intended (not recommended).

which implies that a conformant LRS can accept *Statement*s w/ no or empty `relevantTypes` values.

there are however tests (in `contextagent.js` and `contextgroup.js`) that fail b/c they're expecting *Statement*s with `contextAgents` and `contextGroups` to be rejected if `relevantTypes` is empty.

would appreciate it if somebody can clarify if this a bug in the tests, or a misunderstanding on my part in reading the specs, and if it's the latter, which part of the specs backs the tests.

thanks in anticipation + cheers;
rsn

[1]: https://opensource.ieee.org/xapi/xapi-base-standard-documentation/-/blob/main/9274.1.1%20xAPI%20Base%20Standard%20for%20LRSs.md
[2]: https://opensource.ieee.org/xapi/xapi-base-standard-documentation/-/blob/main/9274.1.1%20xAPI%20Base%20Standard%20for%20LRSs.md#4225-context

**Comment by vbhayden** [comment]
Looking over this one now, it looks like the test seems correct as-is.  As you pointed out, `relevantTypes` as provided in the those tests:
```
var INVALID_RELEVANT_TYPE_IS_EMPTY = {
    contextAgents: [
        {
            objectType: "contextAgent",
            agent: {

                objectType: "Agent",
                mbox: "mailto:player-1@example.com"
            },
            relevantTypes: []
        }
    ]
};
```
```
var INVALID_RELEVANT_TYPE_IS_EMPTY = {
    contextGroups: [
        {
            objectType: "contextGroup",
            group: {

                objectType: "Group",
                mbox: "mailto:player-1@example.com"
            },
            relevantTypes: []
        }
    ]
};
```
is provided by not length 1+, making it invalid for both of those requirements.

**Comment by raif-s-naffah** [comment]
hi @vbhayden,

i see.  b/c the description of a valid value for this property is **"A collection of 1 or more..."** i understood the **"Optional"** requirement to mean either (a) not present (in the JSON string), or (b) present w/ an empty array value.

i understand this may not be mainly an issue for conformance testing but i wonder what would be the risks for an LRS to just ignore such property, as if it was missing, if/when it was found to be an empty array?

**Comment by raif-s-naffah** [comment]
closing - works as expected.
