### ISSUE TITLE
more link validation is wrong

### ISSUE THREAD

**Issue by garemoko** [adlnet/lrs-conformance-test-suite#30]
The spec requires the more link to be a relative URL, however this test suite requires an absolute URL. 

See the comments on this issue: https://github.com/RusticiSoftware/TinCanStatementViewer/issues/16#issuecomment-167552806

**Comment by DavidTPate** [comment]
Here's the relevant section of the [xAPI spec](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#details-21). I definitely see how it could be overlooked as the type is an `IRL` but the comments mention it should be relative.

There's also some parts about links being valid for 24 hours, so I guess that implies the need to have access tokens or other authentication mechanism present solely in the URL as well. I'm not sure how the 24 hour piece would be covered by the conformance tester in its current form.
