### ISSUE TITLE
MIME samples are incorrect

### ISSUE THREAD

**Issue by jezell** [adlnet/lrs-conformance-test-suite#46]
[MIME RFC](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html) says line endings should be CRLF, but the samples don't appear to be using CRLF, maybe an issue with git line normalization since the escaping isn't being explicitly disabled via .gitattributes.

**Comment by cr8onski** [comment]
Is this in test/v1.0.3/templates/attachemnts ?

**Comment by ljwolford** [comment]
I assumed it was the attachment files. I'm assuming git is converting them automatically..I tried adding a few lines in a .gitattributes file but could not get it looking correct. CRLF appears on my Windows machine though.

**Comment by DavidTPate** [comment]
It's related to the Git repository, see [this](https://help.github.com/articles/dealing-with-line-endings/) for some more details.

**Comment by ljwolford** [comment]
Thanks for the link @DavidTPate . If I'm understanding it correctly then, the .gitattributes file should be able to tell any other non-Windows OS to handle the line endings in the repository as CRLF, no matter what their autocrlf setting is?

**Comment by ljwolford** [comment]
Appears to be resolved. Inactive.
