### ISSUE TITLE
Alternate Request Syntax test missing method parameter.

### ISSUE THREAD

**Issue by gavbaa** [adlnet/lrs-conformance-test-suite#81]
In H.Communication2.1-StatementResource.js, there is a test for: `A GET request is defined as either a GET request or a POST request containing a GET request (Communication 2.1.2.s2.b3)`

This test sends a POST to do a GET operation, but does not follow the Alternate Request Syntax rules about the method parameter.  Per the spec: `The intended xAPI method MUST be included as the value of the `method` query string parameter.`

I've read through Communication 2.1.2, and don't see anything that invalidates this rule otherwise.  Is there another part of the spec that allows this POST to surrogate as a GET without the `method` parameter?  Otherwise, I think this particular test is broken.  I'm happy to submit a pull request if someone can confirm there's an issue with this behavior.

**Comment by cr8onski** [comment]
Yes, you are correct.  At one time the spec allowed for a POST with an empty body to be treated as a GET, but that is no longer the case.  

Thanks for bringing this up.  And I'm looking forward to the pr.

**Comment by gavbaa** [comment]
Thanks for verifying.  I think I've done the right thing with pull request #82.
