### ISSUE TITLE
"stored" tests on statements are too strict.

### ISSUE THREAD

**Issue by gavbaa** [adlnet/lrs-conformance-test-suite#93]
Per my reading of the 1.0.3 standard, "stored" is documented as:

> The "stored" property MUST be set by the LRS; An LRS SHOULD validate and then MUST overwrite any value currently in the "stored" property of a Statement it receives.

However, there are several tests in test/v1_0_3/configs/timestamps.js of the form:

```
                    {
                        name: 'statement "template" invalid string in stored',
                        templates: [
                            {statement: '{{statements.default}}'},
                            {stored: INVALID_STRING}
                        ],
                        expect: [400]
                    },
```

This test suite only tests MUST behavior, not SHOULD behavior, correct?  If so, this test and a few others in this same block should be removed, and the rule above is only for the LRS should validate, not must validate.

I'm happy to provide a pull request if I've interpreted the standard correctly.

**Comment by cr8onski** [comment]
Right, I agree those should be taken out.  Please make the pull request to development. Thanks

**Comment by gavbaa** [comment]
Pull request #100 is against the correct branch (development).

**Comment by cr8onski** [comment]
Thank you @gavbaa
