### ISSUE TITLE
"P4W1D" is not a valid ISO8601 4.4.3.2 Duration

### ISSUE THREAD

**Issue by gavbaa** [adlnet/lrs-conformance-test-suite#94]
In test/v1_0_3/configs/durations.js, the following test exists:

```
                    {
                        name: 'statement result "duration" property is valid with "P4W1D"',
                        templates: [
                            {statement: '{{statements.result}}'},
                            {result: '{{results.default}}'},
                            {duration: 'P4W1D'}
                        ],
                        expect: [400]
                    }
```

However, my reading of ISO8601 4.4.3.2 says that this isn't a valid duration.  Taken from here: http://www.uai.cl/images/sitio/biblioteca/citas/ISO_8601_2004en.pdf

> In both basic and extended format the complete representation of the expression for duration shall be [PnnW] or [PnnYnnMnnDTnnHnnMnnS]. 

From that reading, P4W1D isn't valid.  Later parts of 4.4 offer a similar view of the "week" parameter being a standalone option.  Given that, I would say that this test should be removed from the suite.  I can provide a pull request if I've interpreted the standard correctly.

**Comment by gavbaa** [comment]
Ah, I read the test wrong because of the title!  expect [400] is right, and is being tested correctly.  But the test should probably be titled 'statement result "duration" property is _in_valid with "P4W1D"', not valid.

**Comment by cr8onski** [comment]
Good catch.  I'll get the title switched.
