### ISSUE TITLE
Some .wait / helper.genDelay requests are running simultaneously that shouldn't

### ISSUE THREAD

**Issue by gavbaa** [adlnet/lrs-conformance-test-suite#96]
I've noticed that on some of the tests in the suite, requests sometimes come in at the same time that should be dependent on one another.  In all cases, these appear to be based on tests with `.wait(helper.genDelay(...)` calls in them.  To demonstrate, a normal request/response cycle looks like (the number after stderr is the request counter number, to indicate each request in the flow):

```
2016/12/12 06:10:02 stderr: 1 START      POST /statements
2016/12/12 06:10:02 stderr: 1 COMPLETED  status=200
2016/12/12 06:10:02 stderr: 2 START      GET /statements?statementId=f7ffa34c-acdd-48c4-abd3-ca8b11fa0227
2016/12/12 06:10:02 stderr: 2 COMPLETED  status=200
```

But for some tests, I get instead:

```
2016/12/12 06:10:02 stderr: 3 START      POST /statements
2016/12/12 06:10:02 stderr: 4 START      GET /statements?statementId=0de68aa5-560e-4ae8-80c1-0243973a3fc1
2016/12/12 06:10:02 stderr: 4 COMPLETED  status=404
2016/12/12 06:10:02 stderr: 3 COMPLETED  status=200
```

This of course 404s because the GET finishes before the POST has completed.

One such example is Data2.4.6-ContextProperty.js, both tests in this file are structured the same way, and we see this behavior on every instance of that test.  If I comment out the .wait(...) and run the tests in there, the requests all run in order one after the other.

I'm running NodeJS 4.6.2 on OSX Sierra.

**Comment by cr8onski** [comment]
Thanks.  Once I looked, I found the same thing.  This should fix it.
